# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#

version: 2
jobs:
  build:
    docker:
      - image: parthikmodi/tts
    steps:
      - checkout
      - run:
        name: building docker image
        command: |
          docker build -t tts .
          docker images
          docker tag tts $DOCKER_USERNAME/tts
      - run:
        name: pushing docker image
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
          docker push $DOCKER_USERNAME/tts
      - run:
          name: Deploy app to Digital Ocean Server via Docker
          command: |
           ssh -o StrictHostKeyChecking=no texttrack@ritz-tts4.freddixon.ca sudo /usr/local/circleci/deploy.sh