# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#

version: 2
jobs:
  build:
    machine: true
    docker: 
    steps:
      - checkout
      - run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - run: docker build -t tts ./
      - run: docker images
      - run: docker tag tts $DOCKER_USERNAME/tts
      - run: docker push $DOCKER_USERNAME/tts

      - run: 
          name: Deploy app to Digital Ocean Server via Docker
          command: |
            ssh -o StrictHostKeyChecking=no texttrack@ritz-tts4.freddixon.ca sudo /usr/local/circleci/deploy.sh